language: java

matrix:
  include:
    - jdk: openjdk10
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: oraclejdk9
    - jdk: oraclejdk8
    
env:
  global:
  - secure: NP51m1hiFX4cxm2gzLIQVOMUb8/tiJY7KvljYoawnB3NsKOYms2ZfRBMvCnqRROhfisufbohu5bvdPRrOm1DIpeVBTtep3tngdsnbB5yO1hEUXNPhmzVSChbaiEUzj6Fx7/Ct3whhlHkOpTmU1WCFyQ155/qMUsAFJ1yjRj4IeM=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- ".utility/push-output-to-ghpages.sh"

