sudo: false
dist: trusty
language: java

jdk:
- oraclejdk10
- oraclejdk9
- oraclejdk8
env:
  global:
  - secure: NP51m1hiFX4cxm2gzLIQVOMUb8/tiJY7KvljYoawnB3NsKOYms2ZfRBMvCnqRROhfisufbohu5bvdPRrOm1DIpeVBTtep3tngdsnbB5yO1hEUXNPhmzVSChbaiEUzj6Fx7/Ct3whhlHkOpTmU1WCFyQ155/qMUsAFJ1yjRj4IeM=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- ".utility/push-output-to-ghpages.sh"

